# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install antlr 4.5
      run: cd /usr/local/lib; sudo curl -O https://www.antlr.org/download/antlr-4.5-complete.jar; export CLASSPATH=”.:/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH”; cd -;
    #- name: Grant execute permission for gradlew
    #  run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build
    - name: build lexer
      run: make
    - name: clean
      run: make clean
